version: "3"

services:
  server:
    depends_on:
      - "database"
    container_name: "maximize-server"
    entrypoint: ./.docker/entrypoint.sh
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./styles:/app/styles
      - ./prisma:/app/prisma
  database:
    image: postgres:latest
    container_name: "maximize-db"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: maximize
      POSTGRES_PASSWORD: TesteMaximize
      POSTGRES_DB: maximize
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
